name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  servicelocator_sln : "openweathermap.standard.sln"
  package_feed: "https://nuget.pkg.github.com/vb2ae/index.json"
  nuget_folder: "\\packages"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal
    - name: Pack Nuget
      run: dotnet pack ${{env.servicelocator_sln}} --output ${{env.nuget_folder}}
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: published_nuget
        path: OpenWeatherMap.Standard/bin/Release/OpenWeatherMap.Standard.2.1.0.nupkg

